# Generated by Django 3.2.5 on 2021-12-13 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uploadFile',
        ),
    ]
